### ISSUE TITLE
[ASDisplayNode+Layout] Revise subnode orphan checking to run as debug-only assert.

### ISSUE THREAD

**Issue by appleguy** [TextureGroup/Texture#335] opened 2017-06-06 06:27 UTC
Right now, in rare cases it is possible for a node to be orphaned in the hierarchy - when main thread layout is flushed while background calculations are preparing a different layout. Once this is fixed, we should revise the implementation of orphan checking to only run in #if DEBUG and trip an assertion if it occurs.

**Comment by nguyenhuy** [comment] 2017-06-06 18:19
I'm gonna hijack this issue to mention the root cause of orphaned subnodes, as well as subnoes that are never added to the hierarchy. I believe the root cause of these problems is due to the fact that `ASLayoutTransition` accepts it previous layout in the initializer, instead of at commit time (i.e `-commitTransition`). It means that the transition assumes that if it's allowed to proceed on main, the previous layout remains valid which is not true if there was layout pass triggered on main via `-setNeedsLayout`.

There are a couple of things we need to do to fix this problem, as well as to get the layout transition system in a good shape:
- Change `ASLayoutTransition` to accept `previousLayout` at commit time. This will ensure that the diff-ing algorithm has valid inputs.
- Make measure and layout transition passes completely stateless, meaning they don't change any internal states of a node. More details discussed in https://github.com/TextureGroup/Texture/issues/329.

**Comment by nguyenhuy** [comment] 2018-01-16 14:58
Closing per #336.

**Closed by nguyenhuy** 2018-01-16 14:58 UTC
