### ISSUE TITLE
[Layout]Regression – on 2.3 and 2.3.1 ASNetworkImageNode frame is CGRectZero

### ISSUE THREAD

**Issue by rurza** [TextureGroup/Texture#243] opened 2017-05-05 14:13 UTC
The same code on 2.2:
<img width="1440" alt="screen shot 2017-05-05 at 16 05 10" src="https://cloud.githubusercontent.com/assets/2467137/25749010/5bab1d82-31ad-11e7-967a-261f59bec316.png">
after updating to 2.3.1:
<img width="1440" alt="screen shot 2017-05-05 at 16 09 55" src="https://cloud.githubusercontent.com/assets/2467137/25749015/618f5ce0-31ad-11e7-8cbd-152f65d9e3e1.png">
I think it's layout related, so my layout spec:

```
#pragma mark - Layout
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    self.userNameTextNode.style.flexShrink = 1.0f;
    self.userAvatarImageNode.style.preferredSize = CGSizeMake(USER_AVATAR_SIZE, USER_AVATAR_SIZE);
    self.panoramaScrollNode.style.preferredSize = self.style.preferredSize;
    self.gradientImageNode.style.preferredSize = CGSizeMake(self.style.preferredSize.width, self.style.preferredSize.height/4.0f);
    self.scrollbarNode.style.preferredSize = CGSizeMake(self.style.preferredSize.width, 2);

    self.unsplashPhotoImageNode.style.flexGrow = 1.0f;
    self.unsplashPhotoImageNode.style.flexShrink = 1.0f;

    self.unsplashPhotoImageNode.style.minWidth = ASDimensionMakeWithPoints(self.style.preferredSize.width * PHOTO_WIDTH_RATIO);
    self.unsplashPhotoImageNode.style.preferredSize = CGSizeMake(self.style.preferredSize.width * PHOTO_WIDTH_RATIO, self.style.preferredSize.height);

    ASAbsoluteLayoutSpec *scrollAbsoluteLayoutSpec = [ASAbsoluteLayoutSpec absoluteLayoutSpecWithSizing:ASAbsoluteLayoutSpecSizingSizeToFit children:@[self.panoramaScrollNode, self.unsplashPhotoImageNode]];
    
    ASBackgroundLayoutSpec *avatarForShadowSpec = [ASBackgroundLayoutSpec backgroundLayoutSpecWithChild:self.userAvatarImageNode background:self.shadowNode];
    ASStackLayoutSpec *horizontalStackSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                                                                     spacing:2
                                                                              justifyContent:ASStackLayoutJustifyContentStart
                                                                                  alignItems:ASStackLayoutAlignItemsCenter
                                                                                    children:@[avatarForShadowSpec, self.userNameTextNode]];
    
    ASStackLayoutSpec *verticalStackSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                   spacing:10
                                                                            justifyContent:ASStackLayoutJustifyContentCenter
                                                                                alignItems:ASStackLayoutAlignItemsStart
                                                                                  children:@[horizontalStackSpec, self.scrollbarNode]];
    
    UIEdgeInsets infoInsets = UIEdgeInsetsMake(INFINITY, 15, 15, 15);
    ASInsetLayoutSpec *infoInsetSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:infoInsets child:verticalStackSpec];
    
    UIEdgeInsets gradientInsets = UIEdgeInsetsMake(INFINITY, 0, 0, 0);
    ASInsetLayoutSpec *gradientInsetSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:gradientInsets child:self.gradientImageNode];
    
    ASOverlayLayoutSpec *gradientOverlaySpec = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:gradientInsetSpec overlay:infoInsetSpec];
    
    ASOverlayLayoutSpec *overlaySpec = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:scrollAbsoluteLayoutSpec overlay:gradientOverlaySpec];
    return overlaySpec;
}
```
Where self.unsplashPhotoImageNode is the image node which we're talking about.

**Comment by maicki** [comment] 2017-05-05 15:35
@rurza Hey, can you create a small sample that would show us the issue?

Just quickly looking over your example it does not really make sense to set `flexGrow` / `flexShrink`, a `minWidth` and a `preferredSize`. First of all the flexGrow and flexShrink will not do anything as it's not in a stack layout spec. Furthermore what is the `self.style.preferredSize` in the layout spec? Can you not use the `constrainedSize` and based on that layout the node?

**Comment by rurza** [comment] 2017-05-05 15:56
> Just quickly looking over your example it does not really make sense to set flexGrow / flexShrink, a minWidth and a preferredSize.

Well, maybe as flexGrow/flexShrink is some legacy code before this node was a part of scroll node (ASDK 1.x). 
Anyway, as I recall preferredSize is needed, because size of the image isn't known at initialisation time (it's ASNetworkImageNode). Also, this code was already modified countless times after updating to 2.3.

> Can you not use the constrainedSize and based on that layout the node? 

I don't get it :D

**Comment by rurza** [comment] 2017-05-05 16:13
Also, I can paste different cell, maybe this will be a hint for you:
It's used to display ads:
<img width="1440" alt="screen shot 2017-05-05 at 18 09 39" src="https://cloud.githubusercontent.com/assets/2467137/25754021/0f18bcf2-31be-11e7-8796-8d475353c1e1.png">
It's empty because almost every subnode/subview is CGRectZero; whole implementation of the cell:
```Objective-C
//
//  FBNativeAdCellNode.m
//  Background
//
//  Created by rurza on 18/12/2016.
//  Copyright © 2016 micropixels. All rights reserved.
//

#import "FBNativeAdCellNode.h"
#import "CCColorCube.h"
#import "BackgroundButtonNode.h"
@import FBAudienceNetwork;
#import "AsyncMain.h"

@interface FBNativeAdCellNode () <ASNetworkImageNodeDelegate>
@property (nonatomic) FBNativeAd            *nativeAd;
@property (nonatomic) ASTextNode            *titleTextNode;
@property (nonatomic) ASTextNode            *subtitleTextNode;
@property (nonatomic) ASTextNode            *bodyTextNode;
@property (nonatomic) ASTextNode            *sponsoredTextNode;
@property (nonatomic) ASTextNode            *adSocialContextTextNode;
@property (nonatomic) ASButtonNode          *callToActionNode;
@property (nonatomic) ASNetworkImageNode    *adIconImageNode;
@property (nonatomic) ASNetworkImageNode    *adCoverImageNode;
@property (nonatomic) ASDisplayNode         *adChoicesNode;
@property (nonatomic) ASImageNode           *backgroundImageNode;
@property (nonatomic) ASDisplayNode         *blurNode;

@end

@implementation FBNativeAdCellNode

- (instancetype)initWithNativeAd:(FBNativeAd *)nativeAd
{
    self = [super init];
    if (self) {
        self.backgroundColor = [UIColor blackColor];
        self.nativeAd = nativeAd;
        [self setupBackgroundBlurNode];
        [self setupTitleNode];
        [self setupSubtitleNode];
        [self setupBodyNode];
        [self setupSponsoredNode];
        [self setupCallToActionNode];
        [self setupAdIconNode];
        [self setupSocialContextNode];
        [self setupAdCoverImageNode];
        [self setupAdChoicesNode];
    }
    return self;
}

- (void)didLoad
{
    [super didLoad];
    [self.nativeAd registerViewForInteraction:self.callToActionNode.view withViewController:nil];
}

- (void)setupBackgroundBlurNode
{
    ASDisplayNode *node = [[ASDisplayNode alloc] initWithViewBlock:^UIView * _Nonnull{
        UIBlurEffect *blurEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleDark];
        UIVisualEffectView *blurEffectView = [[UIVisualEffectView alloc] initWithEffect:blurEffect];
        return blurEffectView;
    }];
    CGSize screenBounds = [UIScreen mainScreen].bounds.size;
    node.style.preferredSize = screenBounds;
    [self addSubnode:node];
    self.blurNode = node;
}

#pragma mark Text
- (void)setupTitleNode
{
    self.titleTextNode = [self textNodeWithText:self.nativeAd.title font:[UIFont boldSystemFontOfSize:20] andColor:[UIColor whiteColor]];
    self.titleTextNode.style.flexShrink = 1.0;
}

- (void)setupSubtitleNode
{
    self.subtitleTextNode = [self textNodeWithText:self.nativeAd.subtitle font:[UIFont systemFontOfSize:16 weight:UIFontWeightThin] andColor:[UIColor colorWithWhite:0.95 alpha:1.0]];
}

- (void)setupBodyNode
{
    self.bodyTextNode = [self textNodeWithText:self.nativeAd.body font:[UIFont systemFontOfSize:18 weight:UIFontWeightRegular] andColor:[UIColor whiteColor]];
}

- (void)setupSponsoredNode
{
    self.sponsoredTextNode  = [self textNodeWithText:NSLocalizedString(@"Sponsored", @"ad sponsred label") font:[UIFont systemFontOfSize:12 weight:UIFontWeightRegular] andColor:[UIColor colorWithWhite:0.95 alpha:1.0]];;
}

- (void)setupSocialContextNode
{
    self.adSocialContextTextNode = [self textNodeWithText:self.nativeAd.socialContext font:[UIFont systemFontOfSize:16 weight:UIFontWeightThin] andColor:[UIColor whiteColor]];
}

#pragma mark Button
- (void)setupCallToActionNode
{
    BackgroundButtonNode *button = [[BackgroundButtonNode alloc] init];
    [button setTitle:self.nativeAd.callToAction withFont:[UIFont systemFontOfSize:12 weight:UIFontWeightBold] withColor:[UIColor blackColor] forState:UIControlStateNormal];
    [self.blurNode addSubnode:button];
    self.callToActionNode = button;
}

#pragma mark images
- (void)setupAdIconNode
{
    ASNetworkImageNode *imageNode = [[ASNetworkImageNode alloc] init];
    imageNode.URL = self.nativeAd.icon.url;
    imageNode.style.preferredSize = CGSizeMake(40, 40);
    imageNode.cornerRadius = 20.0f;
    imageNode.clipsToBounds = YES;
    imageNode.borderWidth = 2.0f;
    [self.blurNode addSubnode:imageNode];
    self.adIconImageNode = imageNode;
}

- (void)setupAdChoicesNode
{
    ASDisplayNode *node = [[ASDisplayNode alloc] initWithViewBlock:^UIView * _Nonnull{
        FBAdChoicesView *view = [[FBAdChoicesView alloc] initWithNativeAd:self.nativeAd];
        return view;
    }];
    node.style.preferredSize = CGSizeMake(80, 20);
    [self.blurNode addSubnode:node];
    self.adChoicesNode = node;
}


- (void)setupAdCoverImageNode
{
    ASNetworkImageNode *imageNode = [[ASNetworkImageNode alloc] init];
    imageNode.URL = self.nativeAd.coverImage.url;
    imageNode.delegate = self;
    imageNode.cornerRadius = 4.0f;
    imageNode.clipsToBounds = YES;
    imageNode.style.flexShrink = 1.0f;
    imageNode.alpha = 0;
    CGSize screenBounds = [UIScreen mainScreen].bounds.size;
    CGFloat width = screenBounds.width-20.0f;
    imageNode.style.preferredSize = CGSizeMake(width, (CGFloat)self.nativeAd.coverImage.height * (width/self.nativeAd.coverImage.width));
    [self.blurNode addSubnode:imageNode];
    self.adCoverImageNode = imageNode;
}

- (ASTextNode *)textNodeWithText:(NSString *)text font:(UIFont *)font andColor:(UIColor *)color
{
    ASTextNode *textNode = [[ASTextNode alloc] init];
    textNode.attributedText = [[NSMutableAttributedString alloc] initWithString:text attributes:@{NSFontAttributeName:font, NSForegroundColorAttributeName: color}];
    [self.blurNode addSubnode:textNode];
    return textNode;
}

#pragma mark - Network images
- (void)imageNode:(ASNetworkImageNode *)imageNode didLoadImage:(UIImage *)image
{
    if ([imageNode isEqual:self.adCoverImageNode]) {
        AsyncMain(
            [UIView animateWithDuration:0.5 animations:^{
                imageNode.alpha = 1;
            }];
        )
        
        NSArray *colors = [[[CCColorCube alloc] init] extractDarkColorsFromImage:image avoidColor:nil count:1];
        if (colors.firstObject) {
            self.backgroundColor = colors.firstObject;
            self.adIconImageNode.borderColor = self.backgroundColor.CGColor;

        }
        [self setupBackgroundWithImage:image];
    }
}

- (void)setupBackgroundWithImage:(UIImage *)image
{
    ASImageNode *backgroundNode = [[ASImageNode alloc] init];
    backgroundNode.image = image;
    backgroundNode.forceUpscaling = YES;
    backgroundNode.style.flexGrow = 1.0;
    backgroundNode.alpha = 0;
    
    CGSize screenBounds = [UIScreen mainScreen].bounds.size;
    backgroundNode.style.preferredSize = screenBounds;

    [self.blurNode insertSubnode:backgroundNode atIndex:0];
    self.backgroundImageNode = backgroundNode;
    [self setNeedsLayout];
    [UIView animateWithDuration:0.5 animations:^{
        backgroundNode.alpha = 1;
    }];
}

#pragma mark - Layout
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    ASStackLayoutSpec *titleVerticalSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:1 justifyContent:ASStackLayoutJustifyContentStart alignItems:ASStackLayoutAlignItemsStart children:@[self.titleTextNode, self.subtitleTextNode]];
    titleVerticalSpec.style.flexShrink = 1.0f;

    ASStackLayoutSpec *titleAndImageHorizonstalSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal spacing:10 justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsCenter children:@[self.adIconImageNode, titleVerticalSpec]];
    
    
    ASStackLayoutSpec *headerAndCoverVerticalSpec;
    if (self.nativeAd.socialContext.length) {
        headerAndCoverVerticalSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:15 justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStart children:@[self.sponsoredTextNode, titleAndImageHorizonstalSpec, self.adCoverImageNode, self.adSocialContextTextNode, self.bodyTextNode]];
    } else {
        headerAndCoverVerticalSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:15 justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStart children:@[self.sponsoredTextNode, titleAndImageHorizonstalSpec, self.adCoverImageNode, self.bodyTextNode]];
    }
    headerAndCoverVerticalSpec.style.flexShrink = YES;

    
    ASStackLayoutSpec *adAndButtonVerticalSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:30.0f justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStretch children:@[headerAndCoverVerticalSpec, self.callToActionNode]];
    adAndButtonVerticalSpec.style.flexShrink = YES;


    ASInsetLayoutSpec *insetLayoutSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(15, 15, INFINITY, 15) child:adAndButtonVerticalSpec];
    if (self.backgroundImageNode) {
        ASOverlayLayoutSpec *overlayImageLayoutSpec = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:self.backgroundImageNode overlay:self.blurNode];
        ASOverlayLayoutSpec *overlayBlurLayoutSpec = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:overlayImageLayoutSpec overlay:insetLayoutSpec];
        return overlayBlurLayoutSpec;
    }
    return insetLayoutSpec;
}

@end
```

**Comment by rurza** [comment] 2017-05-05 21:28
Some my hints:
in the first example - networkimagenode is a subnode of scrollnode. If I add it to my root node (cell itself) the frame is set properly.

**Comment by maicki** [comment] 2017-05-05 23:05
Do you try update from 2.2.1 to 2.3.1 or from 2.2 to 2.3.1?

**Comment by rurza** [comment] 2017-05-06 07:07
@maicki from 2.2 (didn't even know that there was 2.2.1). I will try 2.2.1

**Comment by rurza** [comment] 2017-05-10 15:55
@maicki I've sent my code to @nguyenhuy :) I can share it in PM on Slack (@rurza)

**Comment by nguyenhuy** [comment] 2017-05-17 16:26
Ok, I finally got time to look at your project. The short answer is that this is not a framework regression but rather a misuse of the framework that happened to work in previous version but doesn't work now.

In your `FBNativeAdCellNode.m`, you add some nodes to a display node (aka `BlurNode`) that hosts a visual effect view. But `BlurNode` doesn’t layout its subnodes whatsoever. Instead, the subnodes are laid out in `-layoutSpecThatFits:` of `FBNativeAdCellNode`. This means the cell node has sublayouts that describe size and position of each subnode, but it doesn’t have the subnodes. On the other hand, `BlurNode` has subnodes but doesn’t have the sublayouts. This is not a recommended way to manage subnodes and their layouts. The direct parent node of some subnodes is the one responsible for laying out its subnodes.

Your setup (accidentally) worked in 2.2 because `BlurNode` and `FBNativeAdCellNode` have an exact same size and position. And in `-[ASDisplayNode _layoutSublayouts]`, we loop through sublayouts of the cell node and modify the frame of whatever layout element stored in each (sub)layout.

However, that’s no longer the case in 2.3. In 2.3, we loop through subnodes, ask for their frame from the internal rect table and assign that frame.

Thanks for taking the time to report and engage. I hope my answer is clear enough. I'm gonna close this ticket. Cheers!

**Closed by nguyenhuy** 2017-05-17 16:26 UTC
Labels: Community Debugging
