### ISSUE TITLE
[ASRunLoopQueue] `processQueue` in ASRunLoopQueue method never Early-exit making CPU usage high

### ISSUE THREAD

**Issue by xilin** [TextureGroup/Texture#518] opened 2017-08-18 12:25 UTC
![screen shot 2017-08-18 at 8 17 09 pm](https://user-images.githubusercontent.com/543395/29458656-bbda8344-8452-11e7-942c-5705e89bdbe2.png)

I'm facing a problem that the `processQueue` method is never Early-exit so that the CPU usage is always 100%.

As you can see in the attachment pic, the count of `_internalQueue` is 3, and all its values are NULL. But the `[_internalQueue compact]` never worked since the `_internalQueue` has a flag of `needsCompaction = false`.

https://github.com/TextureGroup/Texture/blob/cae9517ebe48b68f4e2f5bccfe7c03c207596e07/Source/ASRunLoopQueue.mm#L385

I doubt that if it is because some object enqueue is a weak pointer? Since `NSPointerArray` has a problem that it will not handle weak pointer correctly. See [here](http://www.openradar.me/15396578).

**Comment by cesteban** [comment] 2017-09-07 15:54
Same problem here:

![screen shot 2017-09-07 at 17 42 15](https://user-images.githubusercontent.com/3337678/30172097-1d3ae66e-93f4-11e7-99a3-03efed4aca3f.png)

`_internalQueue` is never drained, and CPU consumption stays at 100% forever.

Did you find a workaround for this @xilin?

**Comment by xilin** [comment] 2017-09-08 02:32
@cesteban Not yet. If we create a fork, I think maybe we could write our own version of compact method to clear the `_internalQueue`.

**Comment by cesteban** [comment] 2017-09-09 14:17
@xilin I believe the solution is not to reimplement `compact`. The problems seems to be that the `NSPointerArray` never gets marked as `needsCompaction`. I'll try to write a failing test or find a way to consistently reproduce the issue. I'll let you know what I find.

**Comment by xilin** [comment] 2017-09-09 14:34
@cesteban Yeah, I think there could be some nodes with weak pointer added into the queue. Looking forward to see a way to reproduce it. It would be very helpful.

**Comment by cesteban** [comment] 2017-09-09 15:41
@xilin Yes, actually `_internalQueue` is a `weakObjectsPointerArray` when it comes to render `ASDisplayNode`'s. In our app the bug always appear while deallocating nodes. The loop that consumes the nodes finds them already deallocated, so it never inserts any nil, and `_internalQueue` is not marked as `needsCompaction`. We can detect this condition and stop the infinite loop.

Working on a failing test that demonstrates the problem. From there the fix should be easy.

**Closed** 2017-09-11 20:32 UTC
