### ISSUE TITLE
Use ASNetworkImageNode how to load https images

### ISSUE THREAD

**Issue by CHENDONGY** [TextureGroup/Texture#548] opened 2017-09-04 02:16 UTC
Now I have an https url image, how to use ASNetworkImageNode to load photos

**Comment by hannahmbanana** [comment] 2017-09-25 18:41
This is a duplicate of https://github.com/TextureGroup/Texture/issues/550, thus it should be closed.

**Closed** 2017-09-29 18:14 UTC
