### ISSUE TITLE
Autolayout + ASViewController with custom view Node

### ISSUE THREAD

**Issue by stephenkopylov** [TextureGroup/Texture#261] opened 2017-05-11 09:36 UTC
Hi all. 
Another bug found.
![screen shot 2017-05-11 at 12 27 12 pm](https://cloud.githubusercontent.com/assets/5202281/25942381/601f16ba-3645-11e7-9d95-0159f233fa2c.png)
with first method of ASViewController Initialization everything works fine. With the second one, when you want to use your custom view-class, autolayout just stops to work.

Otherwise, with frame layout it's working fine. 

[Sample app](https://github.com/stephenkopylov/TextureAutolayout-CustomView)

**Comment by maicki** [comment] 2017-06-20 16:35
@stephenkopylov Hey - This is not a bug per-se, it is just the way Texture is working. The reason for that is that if you initialize the node with a custom view block we use this layer as the layer of the node and do not create a backing layer of class `_ASDisplayLayer`. For layout of subnodes it is actually pretty important that the layer is of class `_ASDisplayLayer` as it forwards all `layoutSublayer` calls to the node. As in your example the backing layer of the root node will be the layer of your custom `UIView` it will never forward the layout calls so the subnode will never be layed out.

I will close this issue as as said it's not a bug it's just the way Texture is currently working. Thanks!

**Closed by maicki** 2017-06-20 16:35 UTC
