### ISSUE TITLE
I am trying to load the network picture when the error reported

### ISSUE THREAD

**Issue by CHENDONGY** [TextureGroup/Texture#550] opened 2017-09-05 09:39 UTC
##### My picture is upgraded using https, using Texture when the picture does not load out. How do I need to be configured to load the image correctly?

_https used a self-signed certificate_

_error_
```
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)
```

**Comment by hannahmbanana** [comment] 2017-09-25 18:40
This is a duplicate of https://github.com/pinterest/PINRemoteImage/issues/405 and should be closed.

**Closed** 2017-09-28 22:03 UTC
